/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as RecepcaoRouteImport } from './routes/recepcao'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as GateRouteImport } from './routes/gate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhookMercadopagoRouteImport } from './routes/api/webhook/mercadopago'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcaoRoute = RecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookMercadopagoRoute = ApiWebhookMercadopagoRouteImport.update({
  id: '/api/webhook/mercadopago',
  path: '/api/webhook/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gate': typeof GateRoute
  '/painel': typeof PainelRoute
  '/recepcao': typeof RecepcaoRoute
  '/super': typeof SuperRoute
  '/api/webhook/mercadopago': typeof ApiWebhookMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gate': typeof GateRoute
  '/painel': typeof PainelRoute
  '/recepcao': typeof RecepcaoRoute
  '/super': typeof SuperRoute
  '/api/webhook/mercadopago': typeof ApiWebhookMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gate': typeof GateRoute
  '/painel': typeof PainelRoute
  '/recepcao': typeof RecepcaoRoute
  '/super': typeof SuperRoute
  '/api/webhook/mercadopago': typeof ApiWebhookMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/gate'
    | '/painel'
    | '/recepcao'
    | '/super'
    | '/api/webhook/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/gate'
    | '/painel'
    | '/recepcao'
    | '/super'
    | '/api/webhook/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/gate'
    | '/painel'
    | '/recepcao'
    | '/super'
    | '/api/webhook/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  GateRoute: typeof GateRoute
  PainelRoute: typeof PainelRoute
  RecepcaoRoute: typeof RecepcaoRoute
  SuperRoute: typeof SuperRoute
  ApiWebhookMercadopagoRoute: typeof ApiWebhookMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcao': {
      id: '/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof RecepcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/mercadopago': {
      id: '/api/webhook/mercadopago'
      path: '/api/webhook/mercadopago'
      fullPath: '/api/webhook/mercadopago'
      preLoaderRoute: typeof ApiWebhookMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  GateRoute: GateRoute,
  PainelRoute: PainelRoute,
  RecepcaoRoute: RecepcaoRoute,
  SuperRoute: SuperRoute,
  ApiWebhookMercadopagoRoute: ApiWebhookMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
